---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=no]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
        name: Prettier

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.28.2
    hooks:
      - id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$

  - repo: local
    hooks:
      - id: dockerfile-provides-entrypoint
        name: cfn_nag
        language: docker_image
        entry: stelligent/cfn_nag:latest
        files: templates/.*\.(json|yml|yaml)$
        args: ["--fail-on-warnings"]
